name       : gnomint
version    : 1.3.0
release    : 1
source     :
    - https://github.com/davefx/gnoMint/archive/1.3.0.tar.gz : 9440a0befa569c6138e2326e2e60840b3837a69f50ca62e1c89c21843dbc9495
license    : GPL-3.0
component  : security
summary    : gnoMint is a graphical X.509 Certification Authority management tool
description: |
    gnoMint is an X.509 Certification Authority management tool
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(sqlite3)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
